name: Run JavaScript Script

on:
  push:
    branches: ["envdemo"]
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment to run against"
        required: true
        type: choice
        default: QA
        options:
          - QA
          - stage

jobs:
  run-js:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'QA' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run script
        working-directory: ${{ github.workspace }}
        env:
          BASEURL: ${{ vars.BASEURL }}
          BROWSER: ${{ vars.BROWSER }}
          USERNAME: ${{vars.USERNAME}}
          PASSWORD: ${{vars.PASSWORD}}
        run: node tests/pac.js
